name: first-workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Step 1
        run: echo "Step 1 complete!"

      - name: Step 2
        run: echo "Step 2 complete!"

  job2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
     
      - name: Cowsays
        uses: mscoutermarsh/cowsays-action@v1
        with:
          text: "hello TechExcelDevOps"
          color: "yellow"
          
