name: loadtest

on:
  workflow_dispatch:

env:
  websiteurl: "https://nckckcah2pqk4-dev.azurewebsites.net/" 

jobs:
  loadtest:
    name: Load Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Actions 
        uses: actions/checkout@v2
          
      - name: Login to Azure
        uses: azure/login@v1
        continue-on-error: false
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: 'Azure Load Testing'
        uses: azure/load-testing@v1
        with:
          loadTestConfigFile: 'loadtest/SampleTest.yaml'
          loadTestResource: 'loadtest-TechExcelDevOps'
          resourceGroup: 'rg-app-TechExcelDevOps'
          env: |
            [
                {
                "name": "website",
                "value": "${{env.websiteurl}}"
                }
            ]
